# Generated by Django 5.2.8 on 2025-11-16 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ['-created_at'], 'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.AddField(
            model_name='goods',
            name='additional_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='goods',
            name='amount_usage',
            field=models.TextField(blank=True, help_text='Amount and usage information'),
        ),
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.CharField(blank=True, choices=[('paints', 'Paints'), ('brushes', 'Brushes'), ('papers', 'Papers/Canvas'), ('tools', 'Tools'), ('mediums', 'Mediums'), ('markers', 'Markers/Ink'), ('pencils', 'Pencils'), ('pastels', 'Pastels'), ('modeling', 'Modeling'), ('textbook', 'Textbook'), ('filming', 'Filming Device'), ('electronic', 'Electronic Device')], max_length=50),
        ),
        migrations.AddField(
            model_name='goods',
            name='course_code',
            field=models.CharField(blank=True, help_text='e.g., DSD-3003-B', max_length=50),
        ),
        migrations.AddField(
            model_name='goods',
            name='major',
            field=models.CharField(blank=True, choices=[('advertising', 'Advertising'), ('animation', 'Animation'), ('3d_animation', '3D Animation and Visual Effects'), ('comics', 'Comics'), ('design', 'Design'), ('film', 'Film'), ('fine_arts', 'Fine Arts'), ('illustration', 'Illustration'), ('photography', 'Photography & Video'), ('visual_studies', 'Visual and Critical Studies'), ('art_history', 'Art History'), ('humanities', 'Humanities and Sciences'), ('others', 'Others')], max_length=50),
        ),
        migrations.AddField(
            model_name='goods',
            name='outcome_description',
            field=models.TextField(blank=True, help_text='Description for outcome images'),
        ),
        migrations.AddField(
            model_name='goods',
            name='payment_methods',
            field=models.CharField(blank=True, help_text='Comma-separated payment methods', max_length=200),
        ),
        migrations.AddField(
            model_name='goods',
            name='professor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='goods',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='GoodsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='goods_images/')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goods.goods')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='OutcomeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='outcome_images/')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='goods.goods')),
            ],
            options={
                'verbose_name': 'Outcome Image',
                'verbose_name_plural': 'Outcome Images',
                'ordering': ['order'],
            },
        ),
    ]
