# Generated by Django 5.2.8 on 2025-11-23 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_message_favorite'),
    ]

    operations = [
    ]
